const rawSpacing = {
  general: {
    "base/1": "var(--base-1)",
    "base/2": "var(--base-2)",
    "base/3": "var(--base-3)",
    "base/4": "var(--base-4)",
    "base/5": "var(--base-5)",
    "base/6": "var(--base-6)",
    "base/7": "var(--base-7)",
    "base/8": "var(--base-8)",
    "base/9": "var(--base-9)",
    "base/10": "var(--base-10)",
    "base/11": "var(--base-11)",
    "base/12": "var(--base-12)",
    "base/13": "var(--base-13)",
    "base/14": "var(--base-14)",
    "base/15": "var(--base-15)",
    "base/16": "var(--base-16)",
    "base/18": "var(--base-18)",
    "base/20": "var(--base-20)",
    "base/24": "var(--base-24)",
    "base/30": "var(--base-30)",
    "base/32": "var(--base-32)",
    "base/40": "var(--base-40)",
  },

  article: {
    "article/max width": "var(--article-max-width)",
    "article/paragraph gap": "var(--article-paragraph-gap)",
    "article/h1 gap": "var(--article-h1-gap)",
    "article/h2 gap": "var(--article-h2-gap)",
    "article/h3 gap": "var(--article-h3-gap)",
    "article/paragraph to list gap": "var(--article-paragraph-to-list-gap)",
    "article/list gap": "var(--article-list-gap)",
    "article/list to paragraph gap": "var(--article-list-to-paragraph-gap)",
    "article/subsection gap": "var(--article-subsection-gap)",
    "article/media to caption gap": "var(--article-media-to-caption-gap)",
    "article/media gap": "var(--article-media-gap)",
    "article/section gap": "var(--article-section-gap)",
    "article/chapter gap": "var(--article-chapter-gap)",
  },

  layout: {},
} as const;

export const spacing = {
  raw: rawSpacing,

  base: {
    1: rawSpacing.general["base/1"],
    2: rawSpacing.general["base/2"],
    3: rawSpacing.general["base/3"],
    4: rawSpacing.general["base/4"],
    5: rawSpacing.general["base/5"],
    6: rawSpacing.general["base/6"],
    7: rawSpacing.general["base/7"],
    8: rawSpacing.general["base/8"],
    9: rawSpacing.general["base/9"],
    10: rawSpacing.general["base/10"],
    11: rawSpacing.general["base/11"],
    12: rawSpacing.general["base/12"],
    13: rawSpacing.general["base/13"],
    14: rawSpacing.general["base/14"],
    15: rawSpacing.general["base/15"],
    16: rawSpacing.general["base/16"],
    18: rawSpacing.general["base/18"],
    20: rawSpacing.general["base/20"],
    24: rawSpacing.general["base/24"],
    30: rawSpacing.general["base/30"],
    32: rawSpacing.general["base/32"],
    40: rawSpacing.general["base/40"],
  },

  article: {
    maxWidth: rawSpacing.article["article/max width"],
    paragraphGap: rawSpacing.article["article/paragraph gap"],
    h1Gap: rawSpacing.article["article/h1 gap"],
    h2Gap: rawSpacing.article["article/h2 gap"],
    h3Gap: rawSpacing.article["article/h3 gap"],
    paragraphToListGap: rawSpacing.article["article/paragraph to list gap"],
    listGap: rawSpacing.article["article/list gap"],
    listToParagraphGap: rawSpacing.article["article/list to paragraph gap"],
    subsectionGap: rawSpacing.article["article/subsection gap"],
    mediaToCaptionGap: rawSpacing.article["article/media to caption gap"],
    mediaGap: rawSpacing.article["article/media gap"],
    sectionGap: rawSpacing.article["article/section gap"],
    chapterGap: rawSpacing.article["article/chapter gap"],
  },
} as const;
